### ISSUE TITLE
Vocal Tract Params

### ISSUE THREAD

**Issue by hyli666** [Sleepwalking/libllsm2#2]
Hi ! Thank you so much for your great job. 
I am new to speech analysis-synthesis field, my question may seem foolish. (#^.^#)
I hope to not only modify f0 and Rd, but also vocal tract filter. I would like to know can I get the vocal tract params (Vocal Tract Filter) by using your library？ If yes, which function  can I use.

**Comment by Sleepwalking** [comment]
Hello, @hyli666 

Thanks for your interest in libllsm2.
You can access the vocal tract magnitude response by pulling `LLSM_FRAME_VTMAGN` out of an LLSM frame.

```c
FP_TYPE* S = llsm_container_get(chunk -> frames[i], LLSM_FRAME_VTMAGN);
int nS = llsm_fparray_length(S);
for(int j = 0; j < nS; j ++)
  printf("%d\t%f\n", j, S[j]);
```

Note that the memory for `S` is managed by `llsm_container`. You should not free it.
