### ISSUE TITLE
Get new pitches for the speech

### ISSUE THREAD

**Issue by jiqizaisikao** [Sleepwalking/libllsm2#3]
Hi,your work is really good.
if we get new pitch for example pitch*=0.9,ignoring formant shift,
How many parameters do we need to modify?

**Comment by jiqizaisikao** [comment]
And also yin algorithm will have big mistake for wave like this:
https://soundcloud.com/iai-top/sine-wave-to-test-yin-pitch
the pitch is 200HZ,but yin will get pitch of 395 396 397....401 402 403 404....
It  happens  when the first harmonic is weak but the second or the third harmonic is too strong.

**Comment by Sleepwalking** [comment]
Hello,

Please refer to [test-layer1-anasynth](https://github.com/Sleepwalking/libllsm2/blob/master/test/test-layer1-anasynth.c), an example of pitch shifting.
