### ISSUE TITLE
How to handle the input audio and output it in real time? 

### ISSUE THREAD

**Issue by bhui** [Sleepwalking/libllsm2#7]
I see the demo test-llsmrt.c about Real-time synthesis. But the F0 is calculate once in the demo.
Is there some solution exist for real time input audio and output in real time?
Thanks~

**Comment by Sleepwalking** [comment]
libllsm2 does not support real-time analysis. The complexity of signal analysis algorithm makes it extremely difficult to run real-time (and even more so when low latency is desired).
You may find general-purpose sound processing libraries such as [Rubberband](https://github.com/breakfastquay/rubberband) and [SoundTouch](https://www.surina.net/soundtouch/) useful (although at lower quality).

**Comment by bhui** [comment]
> libllsm2 does not support real-time analysis. The complexity of signal analysis algorithm makes it extremely difficult to run real-time (and even more so when low latency is desired).
> You may find general-purpose sound processing libraries such as [Rubberband](https://github.com/breakfastquay/rubberband) and [SoundTouch](https://www.surina.net/soundtouch/) useful (although at lower quality).

Thanks for your replay~ 
I would like to change voice's timbre sound like another natual human's voice real time.
I have tried libllsm2 and world vocoder, the f0 estimation cost too much time.
Just change formant without f0 estimation can be work? Did you have some idea about this?
Thank you~!

**Comment by Sleepwalking** [comment]
> Just change formant without f0 estimation can be work?
Unfortunately even formant modification alone requires F0 estimation to be done in the first place (if libllsm were to be used). However, if your application does not involve pitch or time-scale modification, libllsm would be an overkill. A real-time implementation of STFT or linear predictive filter should suffice, and that will be a much simpler solution.

**Comment by bhui** [comment]
> > Just change formant without f0 estimation can be work?
> 
> Unfortunately even formant modification alone requires F0 estimation to be done in the first place (if libllsm were to be used). However, if your application does not involve pitch or time-scale modification, libllsm would be an overkill. A real-time implementation of STFT or linear predictive filter should suffice, and that will be a much simpler solution.

Thank you for your reply, 
Change formant in my audio stream without pitch changed is also my target too.  
Could you show me more details about this?
@Sleepwalking
